### ISSUE TITLE
Provide a better way to model optional intrinsic objects

### ISSUE THREAD

**Issue by hermanventer** [facebook/prepack#1001]
Some intrinsic objects might be null or undefined or both. Currently all intrinsic objects behave like that when compared to null or undefined, but behave like they cannot be null/undefined in other situations. We'd like a less confused story for this.

The basic problem is that we currently can only express mayBeNull/mayBeUndefined/optional by joining objects with null/undefined or both. Joins result in abstract values that are "conditional" operations (c ? x : y), so for a possibly null intrinsic object we might imagine something like (x !== null ? x : null), which can be generalized to x || null.

That does not work, however, since both these expressions simplify to just x, since x is the non null object. So we need something more like `ob = (ob !== null ? x : null)`. As is, that does not work because it is self referential and this causes grief in the serializer.

Probably, the way to is something like `ob = (c ? x : null)` where c is a new kind of value that indicates that `ob !== null` without actually referencing ob. This will require special case checks in a lot of places, so this is hardly ideal either, so please pipe up with alternative ideas.

**Comment by NTillmann** [comment]
As Herman said in the last paragraph, the real issue is that we need to model some kind of union value where the case selection is not done by an external input that could be named.

I find the fact that we currently have a special treatment to allow something like this for intrinsics dubious: I don't know any real intrinsic that actually is optional. The way we currently model the JavaScript engine is exact. Where the optionality comes in is in places where we "abuse" the intrinsic concept for values that are either derived (`intrinsicNameGenerated`), or modeled in some form. I feel that the need to make values optional is more general, not necessarily limited to intrinsics, and it's really about forming a disjunction of values, not just with `null` or `undefined`.
