### ISSUE TITLE
Optionally, bring back "simple" referentialization

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1226]
Currently, we generate a lot of code for captured local variables that are mutated by residual functions. For example, for

```js
(function () {
  let x = 0;
  this.f = function() {
    return x++;
  }
})();
```
we generate
```js
(function () {
  var __scope_0 = Array(1);

  var __scope_1 = function (selector) {
    var __captured = __scope_0[selector];

    if (!__captured) {
      switch (selector) {
        case 0:
          __scope_0[selector] = [0];
          break;

        default:
          throw new Error("Unknown scope selector");
      }

      __captured = __scope_0[selector];
    }

    return __captured;
  };

  var $f_0 = function () {
    var __scope_2 = 0;

    var __captured__scope_2 = __scope_1(__scope_2);

    var __scope_2 = 0;

    var __captured__scope_2 = __scope_1(__scope_2);

    return __captured__scope_2[0]++;
  };

  f = $f_0;
})();
```

(Also notice the redundant `__captured__scope_2` assignment, we have a separate issue for that: #1136)

Instead, a simple variable representing the captured variable could be generated. In fact, that's how things used to work before #643. It should be possible to switch between the two schemes. Introduce a new global option. Eventually, we might add another more local way to switch.

**Comment by sebmarkbage** [comment]
I'm hitting a pretty annoying issue related to this in #1142. When a binding "leaks", it can sometimes be referenced in the initialization path. E.g. if you read from it after it leaked. That means that it must be initialized in the initialization path.

There *might* still be value in initializing it lazily if the read is conditional but the overhead might not be worth it.

The simplest solution to this would be to just opt-out of the laziness for these bindings since they'll often be eager anyway.

**Comment by sebmarkbage** [comment]
@NTillmann The fix to simple closures leads to a bug.

```js
(function() {
  var obj = {};
  console.log(function() {
    obj = {};
  });
  result = obj;
})();
```
->
```js
(function () {
  var $0 = _0; // this is not initialized

  var $f_0 = function () {
    $0 = {};
  };

  var _0 = {};
  console.log($f_0);
  result = _0;
})();
```

The "binding" initialization gets serialized at the top of the generated scope. With the lazy closures, this is a bit strange output but doesn't break because it is lazy.

With simple closures this is eager so it gets assigned a value that isn't initialized yet.

**Comment by NTillmann** [comment]
Hm, another issue is when one combines --simpleClosures and --delayInitializations. That brings out further assumptions in the serializer that closure bindings should get initialized lazily.

**Comment by NTillmann** [comment]
And another issue with simple closures: Prepack may produce wrong code a function spawns multiple closures. The following test case fails:

```js
(function () {
    function f(init) {
        let x = init;
        return function() { let y = x; x = 0; return y; }
    }
    let f1 = f(23);
    let f2 = f(42);
    inspect = function() { return f1() + f2(); }
})();
```

**Comment by NTillmann** [comment]
We have effectively have simple closures for leaked bindings, and otherwise the existing code generation scheme should be reasonable.
