### ISSUE TITLE
Command-line based syntax errors do not print location information

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1239]
Running
```
echo "(){}" | yarn prepack
```
prints a lot of generic gobbledygook. It does mention that there's a syntax error, but it doesn't actually give the error location...
```
Using globally installed version of Yarn
yarn run v1.2.0
warning You are using Node "7.9.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
$ node lib/prepack-cli.js
No sourcemap found at .
Error: syntax error
    at new FatalError (/Users/nikolait/git/prepack/lib/errors.js:48:14)
    at LexicalEnvironment.concatenateAndParse (/Users/nikolait/git/prepack/lib/environment.js:1217:23)
    at LexicalEnvironment.executeSources (/Users/nikolait/git/prepack/lib/environment.js:1256:41)
    at Serializer._execute (/Users/nikolait/git/prepack/lib/serializer/serializer.js:103:52)
    at Serializer.init (/Users/nikolait/git/prepack/lib/serializer/serializer.js:143:23)
    at prepackSources (/Users/nikolait/git/prepack/lib/prepack-standalone.js:83:33)
    at ReadFileContext.callback (/Users/nikolait/git/prepack/lib/prepack-node.js:70:61)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hermanventer** [comment]
The "No sourcemap found at ." message is something we can do without as well.

**Comment by baptistemanson** [comment]
Hi all,
I'm getting my feet wet on that task ;). 

Here is what I understood:
- stdin is read by prepack-stdin only when there is [no file provided as input](https://github.com/facebook/prepack/blob/master/src/prepack-cli.js#L223)
- prepack-stdin still has logic to[ check files and sourcemaps](https://github.com/facebook/prepack/blob/master/src/prepack-node.js#L35) that needs to be removed
- this logic is present only because prepack-stdin was [copied and pasted](https://github.com/facebook/prepack/blob/5537534243fe0ecd3f137d3b9820a82130e629bb/src/prepack-node.js) from prepack-file
- stdin unit tests [never passed](https://github.com/facebook/prepack/pull/784/files)

So I think I have to:
- remove the logic around reading files and sourcemaps in prepack-stdin
- fix the unit tests

Am I on the right tracks?

**Comment by hermanventer** [comment]
We do want the user to be able to give the location of the source map as a flag when using stdin. We also want to give an error when the location does not exist. What we don't want to do is to complain about source maps when the flag has not been specified. The stdin unit tests are working as intended.

So, to fix the "No sourcemap found..." problem, you need to suppress the message if the flag was not specified.

The other problem is that the syntax error causes an uncaught FatalError. Instead, we'd like a nice compiler diagnostic that is printed out with a source location (obviously one that does not include a file name).

**Comment by baptistemanson** [comment]
Thank you!
I will make a PR.
