### ISSUE TITLE
Serialization problem with additionalFunctions

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#1346]
Using this input when trying to serialize the output to `jsx` with `reactEnabled`:

```js
(function () {
  
  function Component2() {
    // nothing here
  }
  
  function MyComponent() {
    return (
      <div ref={() => {
        var foo = <Component2 />
      }} />
    );
  }
  
  __registerReactComponentRoot(MyComponent);
  
  global.result = MyComponent;
})();
```

The above `MyComponent` function is evaluated as an additionalFunction, but the closure inside the function is not evaluated but still serialized:
```js
() => {
  var foo = <Component2 />
}
```

The issue is that this will cause an invariant error because it tries to replace `<Component2 />` with `__captured__scope_2[0]` during the `ClosureRefReplacer`. Unfortunately, this is invalid syntax in JSX (you can't have `< __captured__scope_2[0] />`) because of the computed properties. 

Why it's even being put in a captured scope here? The reference to `Component2` never changes and remains constant. Could we serialize `__captured__scope_2` to a variable reference rather than using computed properties directly?

**Comment by cblappert** [comment]
The logic for creating those `__captured__scope` references should only kick in when the corresponding `ResidualFunctionBinding` is modified. Since Component2 is constant, we should be serializing it to a var, so either there is a bug in the `Referentializer` or something is setting `Component2` to be `modified`.
