### ISSUE TITLE
Do/While Loop Condition is executed before the body of the loop

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#1677]
```js
var n = __abstract('number', '(2)');
var i = 0;
do {
  console.log(i);
} while (i++ < n);
```
->
```js
  var _$0 = 0;

  do {
    var _1 = _$0 + 1;

    console.log(_1);
    var _$1 = _1;
    _$0 = _$1;
    var _6 = 2;

    var _5 = _$0 < _6;

    var _$2 = _5;
  } while (_$2);
```
This should print 0, 1, 2 but it'll print 1, 2 instead because it increments the loop number in the beginning of the loop instead of the end.

**Comment by hermanventer** [comment]
The fundamental reason for that is that we generate the loop body from the fixpoint, which is a common approximation of the state at the end of each loop iteration. Since the i++ is part of the loop body, the value of i that ends up in console.log is fixed and becomes insensitive to its position relative to the increment.

To fix this, we would need to have a separate abstract state for each temporal point. I.e. every generator entry should carry an abstract state with it.

For now, this seems more work than is reasonable to take on in the near future.

**Comment by sebmarkbage** [comment]
For this particular issue, wouldn't it be enough to evaluate the condition as part of the body?

This works fine:

```js
var n = __abstract('number', '(2)');
var i = 0;
do {
  console.log(i);
  var condition = i++ < n;
} while (condition);
```

**Comment by hermanventer** [comment]
Astute observation. It turns out that the problem was that the loop termination test was not emitted into the loop body generator at the correct temporal point.
