### ISSUE TITLE
Prepack hangs on recursive code

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1800]
Here is the minimal repro I could manage:

```js
require("react");

__evaluatePureFunction(function() {
  var React = require("react");

  var re = new RegExp("");

  function parse(uri, uriToParse) {
    var result = new URIBase(null);
    if (result > 1) {
      uriToParse.badMethod();
      return result;
    }
    return result;
  }

  function URIBase(uri) {
    parse(this, uri);
  }

  function App(props) {
    var uri = props.something;
    var href = void 0;
    if (parse(null, uri)) {
      href = new URIBase(uri);
    } else {
      href = new URIBase("#");
    }
    re.test(href);
    return React.createElement("a");
  };

  __optimizeReactComponentTree(App, {
    firstRenderOnly: true
  });

  module.exports = App;
});
```

It hangs.

I'm not sure if Prepack is *supposed* to hang on infinite recursion?
Oddly, removing `return React.createElement("a");` in the end fixes the issue.

I tried to create other recursive examples but Prepack didn’t seem to have an issue with them.

Call stack:

<img width="361" alt="screen shot 2018-04-27 at 7 05 37 pm" src="https://user-images.githubusercontent.com/810438/39377727-082b8f56-4a4e-11e8-95fc-f916a83e5ccd.png">

**Comment by NTillmann** [comment]
It takes a very long time before the visitor is even engaged, so I suspect some giant datastructures are being built up. The visitor might have a quadratic behavior in call chain depth, so that might indeed seem like it's taking forever... In any case, I'll take another look at this, at the very least I want to make sure that there is indeed progress, maybe add a progress indicator, or identify what exactly is enormous.

**Comment by gaearon** [comment]
Seems like this got fixed. I'll file if this comes up again.
