### ISSUE TITLE
Missing .derive() around Error message toString

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1841]
This test fails. For some reason, the Prepack front-end decides to introduce a timeless `.toString` call on the `Error` object. Prepack then proceeds to rearrange the assignment to the `.name` property.

```js
(function () {
    let x = global.__abstract ? __abstract("string", "('abc')") : 'abc';
    let e = new Error(x);
    global.text = e.toString();
    e.name = "Surprise";
    inspect = function() { return global.text; }
})();
```

**Comment by NTillmann** [comment]
Found while trying to fix #1821; this might block the fix.

**Comment by NTillmann** [comment]
@hermanventer did a great analysis of what's going on.

There are two lines that are not quite right:
https://github.com/facebook/prepack/blob/f7b0cb8ecd099e5fc5ef8a8b6aff8bf791664782/src/intrinsics/ecma262/ErrorPrototype.js#L45
https://github.com/facebook/prepack/blob/f7b0cb8ecd099e5fc5ef8a8b6aff8bf791664782/src/intrinsics/ecma262/ErrorPrototype.js#L54

What happens here is that when the `name` or `message` property are abstract, then this function falls back to just calling `toString` on the entire error object. That is wrong, as `toString` on an error object is not a stateless operation.

So here is what should happen to make it safe:
- Check if the name/message abstract values in question in fact are known to be of type `StringValue`.
- If not, fail via `throwIfNotConcrete`.
- Instead of doing a concrete concatenation, do a template-based abstract concatenation. This is now a safe thing to do, as we know that the constituents are values of the right types.

**Comment by NTillmann** [comment]
To reproduce the issue:

Take the code snippet I mentioned above, put it as `Issue1841RegressionTest.js` file under test/serializer/abstract, and run `yarn test-serializer --filter Issue1841`.

**Comment by lxfind** [comment]
We probably don't want to do an abstract concatenation here, because according to the spec, if either name or message is abstract value, we have to evaluate that value, check if it's undefined, and if so replace with it with something else. That would make the generated code too long. I propose we just remove those two checks regarding the abstract value, and not handle prepacking Error object with abstract name/message at all.
btw it also misses one step (Step 7) according to http://es5.github.io/#x15.11.4.4
Apparently the ECMA website missed this step.
