### ISSUE TITLE
Are Effects' createdObjects including parent generator's createdObjects?

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1855]
I think I've come across different test cases where I have seen both.
This is actually semantically relevant right now, as `Generator._generatorEffects` issues, or doesn't issue, calls to `emitPropertyModification`.

This related to #1826.

**Comment by hermanventer** [comment]
When two effects are joined together, or composed together, the result does have a set of created objects that is the union of the two. This does not apply, however, to the effects that get put into the result of Generator.fromEffects. Those always seem to have empty sets of created objects.

**Comment by hermanventer** [comment]
It also turns out that when completions are rewritten as a result of reaching join points (for example, removing all return completions from a joined completion tree), the invariants established by the original join will no longer hold. This is not an accident, but necessary. Re-establishing the invariants will take effort, so we need to think carefully about relying on them.

**Comment by NTillmann** [comment]
I am not sure I understand what that means. What _can_ the back-end assume? Are you saying the created-objects information should not be relied on for anything right now?

**Comment by NTillmann** [comment]
This issue seems no longer relevant after the recent big refactoring.
(What might be relevant is a similar question for nested optimized functions, but that's for another time.)
