### ISSUE TITLE
Object.assign() on a potentially null argument in optimized functions

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1865]
Serializer test:

```js
(function() {
  function fn(arg) {
    var a = arg ? arg.a : null;
    var b = arg ? arg.b : null;
    return { a, b };
  }

  if (global.__optimize) global.__optimize(fn);

  global.inspect = function() {
    return JSON.stringify([fn(null), fn({ a: 1, b: 1 })]);
  };
})();
```

It breaks because the output looks like

```js
// ...
var _$3 = _$2.Object;
// ...
var _$7 = _$3.assign;

var _2 = function (arg) {
  var _4 = _$7(arg); // <-- Object.assign() on maybe null!

  if (arg) {
      var _$0 = _4.a;
  }

  if (arg) {
      var _$1 = _4.b;
  }

  // ...
}
```

If there was only one `arg ? arg.something : null` the test would pass because the `assign()` call would be *inside* the `if (arg)` condition. But it looks like because there are two, the `assign()` call gets hoisted outside the condition to where it’s not safe to run it.

**Comment by trueadm** [comment]
@sebmarkbage will know about this, as he added this `Object.assign` usage. Maybe there was an unforeseen side-effect from doing it here?

**Comment by sebmarkbage** [comment]
Just to be clear, this has nothing to do with assign. It's just a convenient alias for ToObject.

I think the particular issue is that this is not temporal https://github.com/facebook/prepack/blob/838c26d7a0bfb3bba8e941889b756e7050b51184/src/methods/to.js#L445

I originally didn't want these to leak because it serializes suboptimal code. It should almost always unwrap the ToObject wrapper and just refer to the original. This is one of those cases where this should never be serialized as a call because the ToObject is already implied by the property access.

This is extra bad because it somehow reused the *same* object but this should actually be two objects if it's a primitive. Which it would be if it was unwrapped by the property access as intended. I don't know why this isn't causing two objects. Is it some kind of abstract value equality test?

cc @hermanventer

**Comment by gaearon** [comment]
I sent https://github.com/facebook/prepack/pull/1879 for the suboptimal code concern

**Comment by gaearon** [comment]
>but this should actually be two objects if it's a primitive

Is this a correctness problem? I understand the output is suboptimal, but can you give me an example where it matters whether we created one or two. As long as it's not exposed to the user why does it matter (aside from the obviously bad hoisting)?

**Comment by sebmarkbage** [comment]
```js
Object.defineProperty(String.prototype, 'a', { get() { return this.cache || this.cache = {}; } });
Object.defineProperty(String.prototype, 'b', { get() { return this.cache || this.cache = {}; } });
fn('foo');
```

Not saying anyone would do that but hard to say what else can be an issue.

It's more likely if the object does leak. That's what the call to Object.assign was meant to fix in the first place. The scenarios when it leaks to user space. So it is possible. E.g. `Object.assign('foo');`

**Comment by gaearon** [comment]
Here is another test case for this based on product code:

```js
(function() {
  function fn(arg) {
    return arg != null && arg.x && arg.y;
  };

  if (global.__optimize) __optimize(fn);

  global.inspect = function() {
    return JSON.stringify([
      fn(null),
      fn(undefined),
      fn({x: false, y: 5}),
      fn({x: 5, y: 10}),
    ])
  }
})();
```

**Comment by gaearon** [comment]
This got fixed in https://github.com/facebook/prepack/pull/1925.
