### ISSUE TITLE
Undefined variable in the output with conditionals

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1867]
Broken serializer test:

```js
(function() {
  function fn(arg) {
    if (arg !== null) {
      if (arg.foo) {
        return 42;
      }
    }
  }

  if (global.__optimize) {
    __optimize(fn);
  }

  global.inspect = function() {
    return JSON.stringify([
        fn(null),
        fn({}),
        fn({foo: true}),
    ]);
  };
})();
```

**Comment by sb98052** [comment]
This bug is triggered by nested abstract tests in optimized functions that end in possibly normal completions. In the above example, `if arg !== null` can be replaced by any abstract test, e.g. `if arg.bar`. There are two issues at the join point at the exit from the optimized function, when the normal and abrupt completion paths are merged (`joinEffectsAndPromoteNested -> joinGenerators`).

1) The join condition in the merge contains a conditional captured temporally in the inner of the two tests. The serializer does not see the declaration for this abstract value and bails with the invariant failure reported in this issue.

2) The join condition is incomplete, and contains only the innermost condition, instead of the entire path condition, leading to the generation of incorrect code.

A brief exchange with @hermanventer suggested that fixing this might get lumped into some refactoring and design work that he will be doing.
