### ISSUE TITLE
Try a simpler _generatorOfEffects approach

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1945]
Collapse the effects tree of an optimized function similar to what happens at the program level;
only emit property/binding modifications for objects not created in the optimized function.

With the recent change to how the exceptional code path is emitted (#1889), the resulting code might not be too bad. We might need to do more work to reduce conditional expressions with common conditions to condition statements (#1946) to make it really shine.

If the visitor and serializer would no longer have to deal with applying and undoing effects, then that would Prepack's backend much simpler and more reliable.

**Comment by cblappert** [comment]
I'm pretty sure that will still be too much output for React Compiler. Part of the reason the original logic is so complicated is because they had a lot of cases where optimized functions captured values (and possibly modified them) but those values weren't needed by anything afterwards. The issue there is orthogonal to exceptional code paths.

See #1093

**Comment by NTillmann** [comment]
I am not sure how #1093 is relevant here. Unreferenced values should not be visited by anyone ever.

**Comment by NTillmann** [comment]
This was addressed by the big refactoring.
