### ISSUE TITLE
Not all bindings getting havoced

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2001]
While thinking about snapshots and how to address #1973, I started studying the havocing code. I created this test that I thought should work:
```js
(function () {
    function f(g) {
        let x = 23;
        function h() { x = x + 42; }
        g(h); // <-- this havocs h, and should therefore havoc all relevant bindings?
        return x; // and then this should return the dynamically updated value, not 23
    }
    global.__optimize && __optimize(f);
    global.inspect = function() { return f(h => h()); }
})();
```

However, the test doesn't work, because we skip havocing bindings of the innermost environment record, starting only at the parent:
https://github.com/facebook/prepack/blob/41e9dcb39837618bbe7376d42db0b92ae8d24a7e/src/utils/havoc.js#L303

@sebmarkbage , am I missing something, or just the `.parent` just be removed?

(Fixing that brings up some other issues in how `serializeBinding` works, but before diving in that area, I want to make sure I understand intentions.)

**Comment by sebmarkbage** [comment]
This seems like a mistake. It works with `var` which would be one environment up. It's just because `let` is block scoped.

It is subtle because we don't want to havoc the environment inside the function. It's tricky to get right. I had a lot of bugs. E.g. you want to make sure that the pure function itself doesn't havoc but things in its scope can havoc.

Try and it and see what breaks? :)
