### ISSUE TITLE
Havocing and Alias Problems of Letting Objects go to topVal

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#2179]
I figured I'd write this down so we know to fix it at some point. I don't know of any real issues yet outside of widening. I'll look into fixing widening but this is subtle and may happen in other places.

Currently, making something `ValuesDomain.topVal` with a `TypesDomain` that includes objects, means that it could be *any* object.

Lots of operations can yield topVal where we just forget the more specific knowledge we once had.

https://github.com/facebook/prepack/blob/a10ac631b4d1f1a0ea8384fb15ff821691b5941c/src/domains/ValuesDomain.js#L100

This issue surfaces in PureScope mode, where we assume that modifications to such values are ok, as long as we havoc the value.

```js
var obj1 = {x:1};
var obj2 = operationThatReturnsTopVal(obj1);
obj2.x = 2; // havocs obj2
result = obj1.x;
```

If obj1 and obj2 might be the same, the havocing of obj2 must also have havoced obj1. Otherwise, we'll have incorrectly assumed that `obj1.x` is `1` and inline it.

Now this is still mostly fine. Because for abstract values we actually havoc all inputs to the abstract value by havocing the args.

https://github.com/facebook/prepack/blob/master/src/utils/havoc.js#L449-L451
(If the ValuesDomain, is non-top we don't actually have to do this, we should instead havoc the values.)

So typically `obj2` would be represented by an `AbstractValue` whose `.args` property includes `obj1` in it since it'll be derived using it somehow.

This is not always the case though.

One way we could enforce this, we could add an invariant that `AbstractValue` always either have a non-top `ValuesDomain` or has non-empty `args`. This will flush out some places where this is not true (such as widening).

**Comment by NTillmann** [comment]
It seems to me that your `operationThatReturnsTopVal` should be a temporal thing which triggers havocing of its arguments as appropriate when its emitted.

If it's not a temporal thing, then I assume that in your example `obj2` is an abstract object value? If `obj2` could just potentially alias `obj1`, then indeed havocing `obj2` should extend to `obj1`.

Side note: If the intention is to allow the abstract value that represents `operationThatReturnsTopVal` to also create a new object, then we have a new problem. First of all, some discussion might be in order whether we really want to allow this as a timeless operation, since object-creation can be seen as a timed event. And in fact that would present a problem: For objects, Prepack tracks object-creation via the `createdObjects` property in effects. However, no such thing happens for abstract (object) values. The creation information is essential for the serializer to place object creations into the right scope, and only create an object once.

**Comment by sebmarkbage** [comment]
Basically this is just a fallback mechanism because we haven’t covered all cases. There are too many things that generate topVal objects right now since and values domain can choose to go to topVal almost at any time.

It’s not always necessary to havoc them as a result. Eg a condition of a topVal object and a concrete object will yield a topVal but we wouldn’t want to havoc all concrete objects in any such case. Only if it actually ends up escaping which is what havocing the args helps with.

I agree that this is undermodeled but a safer fallback than not havocing anything.

**Comment by sebmarkbage** [comment]
One possible improvement is that we keep known objects in the ValuesDomain whenever we go to top so that we know that it might at least be one of these but also others. That way we can keep a reference back to them in case we need to havoc.
