### ISSUE TITLE
Serializer _getReferentializationScope invariant 

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2248]
Given this test case:

```js
function fn(str, start, length) {
  var size = str.length;
  var posA = 0;
  if (start > 0) {
    for (; start > 0 && posA < size; start--) {
      posA += 1 + str.charCodeAt(pos);
    }
    if (posA >= size) {
      return "";
    }
  }
}

__optimize(fn)
```

We run into this invariant: https://github.com/facebook/prepack/blob/master/src/serializer/Referentializer.js#L168

**Comment by cblappert** [comment]
I just tried this on master, and I get a different invariant:
![image](https://user-images.githubusercontent.com/3744743/42649069-7aebef86-85bd-11e8-9d47-769abc507d6b.png)

Do you have some local changes or a branch to check out?

**Comment by cblappert** [comment]
Just looked in the debugger, and it seems like we're trying to referentialize `str` as if it were a binding and not an argument.

Looks like there weren't any tests before that tried to mutate/leak arguments. I should be able to put up a PR soon.

**Comment by NTillmann** [comment]
Make me a reviewer of the PR. Referentialization and arguments indeed hasn't been given any thought yet.

**Comment by cblappert** [comment]
Actually it's a little worse then I originally thought, it looks like we never visit any bindings local to optimized functions unless they are captured by some nested residual function that is also visited. Looks like we probably want to visit bindings that are needed for loops as well, have to think about how that should work a little.

**Comment by cblappert** [comment]
Debugged a bit more, and it seems ilke we do actually do the right thing here in the visitor and for loop code, but the generator containing the dummy function referencing the bindings gets lost on [this line](https://github.com/facebook/prepack/blob/37d692480b306e50eb065b8931b89ad7c3c1828d/src/realm.js#L1062) where we decide to drop the generator instead of applying it. This seems like another variant of the issue where generators/generator entries go missing that @hermanventer is working on.

Working on a fix now, but it'll probably take a few days.
