### ISSUE TITLE
Error with fixpoint_rerun - "modified in a nested context"

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2262]
With this test case and this PR applied (https://github.com/facebook/prepack/pull/2261): 

```js
function fn2(obj, x) {
  if (obj.cond1) {
    throw new Error("Error");
  }
  return Object.assign({}, x, { a: 1 });
}

function fn3(obj, x) {
  if (obj.cond2) {
    throw new Error("Error");
  }
  return Object.assign({}, x, { b: 1 });
}


function fn(obj, x) {
  var a = fn2(obj, x);
  var b = fn3(obj, x);

  if (obj.cond3) {
    var c = Object.assign({}, a, b);

    return c.a + c.b;
  }
  throw new Error("Error");
}

this.__optimize && __optimize(fn);

inspect = function() {
  return fn({
    cond1: false,
    cond2: false,
    cond3: true,
  }, { a: 0, b: 0 })
}
```

I get this error locally:

```
Error: PP1006: Internal slot _isPartial modified in a nested context. This is not yet supported. at 12:23 to 12:25
```

**Comment by NTillmann** [comment]
I wonder which operation makes an object partial.
But in any case, the `_isPartial` internal slot should just be ignored during serialization.
The fix is likely to filter out such internal slots and suppress this call:
https://github.com/facebook/prepack/blob/e170c37aaa996c75cb166671c5b6af442a227d5c/src/utils/generator.js#L516

All internal slots that start with an underscore fall into that category.
