### ISSUE TITLE
Dubious warning with nested optimized functions

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2266]
Trying to Prepack this...
```
function outer() {
  function inner() { return 42; }
  __optimize(inner);
  return inner;
}
__optimize(outer);
```
yields the following warning with has no meaning to the end-user:
```
side-effects from mutating a property "1"
```

**Comment by cblappert** [comment]
Probably what's happening here is that the internal map recording functions to optimize is getting mutated, so we should suppress that warning on mutations to our internal global properties.

Also we probably don't need the map recording optimized functions to be a global property because we always unconditionally optimize functions even if the `__optimize` call is conditional.
