### ISSUE TITLE
prepack.io/repl.html doesn't show code in presence of warnings

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2285]
Check out:
https://prepack.io/repl.html#BQMwrgdgxgLglgewgAmASmQbwFDOQGwFMZkFkBeLAXwG5dlxp4kH0t68EA6ADwuQBMAZjp48AJ2JhxKBKORV6AfSUIADvAC2cAF6FQaeQHN8CAEYBDfFxD8QdKmnQ0gA

Perfectly prepackable, but the (newly introduced) warning causes the website to not show the generated code.

**Comment by enzoferey** [comment]
Hi @NTillmann, I would love to take this issue !

As far as I see this would be something like adding another clause here: https://github.com/facebook/prepack/blob/067a378227d0c2034aa963c8981cf243356f349a/website/js/repl.js#L170 with a "warning" type branch and modifying: https://github.com/facebook/prepack/blob/067a378227d0c2034aa963c8981cf243356f349a/website/js/repl-worker.js#L40 to dispatch a "warning" instead of just success/error, right ?

I will need to look further on Prepack code to know how warnings are formatted in order to know which kind of result to dispatch.

Do you we want to display the generated code as well as the warning message underneath ?

**Comment by bencooper222** [comment]
Shouldn't this be closed or is there still something I can help with?

**Comment by NTillmann** [comment]
Already fixed. Thanks!
