### ISSUE TITLE
Failed nested optimized function case #3

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2392]
Another failing case with invariants `invariant(this._activeGeneratorStack.includes(reason));` and  `invariant(this._waitingForBodies.size === 0);`:

```js
function fn(x, obj, cond, cond2, cond3, cond4) {
  var arr = Array.from(x);
  var a;
  var b;
  var res;

  if (cond) {
    a = obj.a;
    if (cond2) {
      b = obj.b;
      if (cond3) {
        res = arr.map(function(item) {
          return cond4 ? a : b;
        });
      }
    }
  }
  return res;
}

__optimize(fn);
```

**Comment by cblappert** [comment]
This actually seems related to the bit of code I was confused by in the previous PR: #2383. It looks like what's happening is `fn` declares a derived ID in some nested generator that isn't in the parent chain of the nested optimized function (even though the body is still active in the emitter). I have to think a bit about how to solve this because all of my quick solutions cause other test cases to fall over.
