### ISSUE TITLE
Nested optimized function invariant #4

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2398]
Test case, but this might be the same issue as https://github.com/facebook/prepack/issues/2358:

```js
function fn(props, cond) {
  var arr = Array.from(props.x);
  var newObj;
  
  if (cond) {
    var _ref8;
    var value = (_ref8 = props.feedback) != null ? ((_ref8 = _ref8.display_comments) != null ? _ref8.ordering_mode : _ref8) : _ref8;

    var fn2 = function() {
      return value;
    }

    var res = arr.map(function(item) {
      return item[value];
    });
  }

  return [res, fn2];
}

global.__optimize && __optimize(fn);

global.inspect = function() {
  return true;
};
```

**Comment by NTillmann** [comment]
The issue here is that `value` is referenced by `fn2` (a residual function) and the anonymous _optimized_ mapping function, and the serializer (wrongly) concluded that the target body where `value` should be emitted to is global code, and that trips up invariants. The will would be to make the serializer realize that the target body for `value` should be somewhere in the optimized function `fn`. So the change would be to `_getTarget`, directly or indirectly.

**Comment by cblappert** [comment]
Right, I didn't read PR #2346 too closely. What we want to do for optimized functions that need to be evaluated at a particular time/environment is to materialize any values that they use before.

I don't think the change needs to be reverted since it's already guarded by a flag (although we might want to turn that flag off by default if it isn't already).
