### ISSUE TITLE
Why Does Prepack Need Mocks/Shims?

### ISSUE THREAD

**Issue by ilyaigpetrov** [facebook/prepack#614]
I want to mark that `global.window` is only accessible at runtime, so Prepack should "transport" it to runtime without substitution or "speculation" about its value (including props/children, etc.).

Input:
```js
'use strict';
__assumeDataProperty(global, 'window', __abstract());
console.log(window.document);
```
Output:
```console
This operation is not yet supported on abstract values ::global.window and ::global 
__IntrospectionError
```
Expected:
```js
(function () {
  var _0 = this;

  var _1 = _0.window;

  if (_0.window !== _1) {
    throw new Error("Prepack model invariant violation: " + _0.window);
  }

  console.log(_1.document); // Access props only at runtime for unknown abstract variables!
}).call(this);
```

**Comment by cblappert** [comment]
Without additional knowledge, Prepack does not necessarily know it is safe to do that relocation. An abstract object represents an arbitrary object which means the properties could have getters/setters that modify the program state arbitrarily. You could use `__makePartial(window)` which assumes that all unknown properties are simple data properties, but that only goes one nesting-level deep.

**Comment by ilyaigpetrov** [comment]
I still don't get it.
Let's imagine there is an object `global.leftUserEye = { color, ... }` which is known only at runtime.
Let's take that I run Prepack on a script that accesses `global.leftUserEye` somewhere in the code, but not everywhere -- so we have space for a compile-time optimization.
I want Prepack to optimize script, but transfer all interactions with `global.leftUserEye` to output intact.
Why I can't tell Prepack to leave `global.leftUserEye` intact, why I have to shim it?

**Comment by cblappert** [comment]
Not sure what you mean by shim in this case. The `__abstract` or `__makePartial` functions are the way you "tell" Prepack things about specific objects.

For the case you just described, you could add the lines: 
```javascript
// Tells Prepack global has a property leftUserEye that is some object we don't know anything about
global.leftUserEye = __abstract({});
// Tells Prepack that leftUserEye has just a bunch of data properties (that don't have getters/setters with visible side effects).
__makePartial(global.leftUserEye);```

You have to tell Prepack that these properties exist and won't have visible side effects because otherwise you could contrive a situation where accessing `global.leftUserEye` could throw or modify arbitrary variables because there is a getter on that property.

What if in the environment, `leftUserEye` was setup like this.
```javascript
global.leftUserEye = Object.defineProperty(global, 'leftUserEye', 
{ 
  get: function() { global.foo = 5; throw new Error(); } 
});
``` 
Then it would be incorrect for Prepack to just emit the interactions of `global.leftUserEye` in the output, because Prepack may then assume the wrong control flow or wrong value for `global.foo` in the final program.

**Comment by ilyaigpetrov** [comment]
Ok, side effects from accessing `window.*` make optimization uneasy:
```js
'use strict';
let foo = `Pi is ${ calculatePi({ precision: 99999 }) }`;
console.log(window.document); // May change the value of `foo` as a side effect!
console.log(foo); // Can we use optimized `foo` here? You never know.
```
It means Prepack is difficult to use with functions without source codes, because Prepack can't know if they have side effects.

1. Ideally I want to be able to tell Prepack: "Accessing object foo.* may only change vars X and Y and it can't have any other side effects". But I think I ask too much yet.

2. Now I want to lie to Prepack by telling that `window.*` has no side effects:
```js
'use strict';
__residual('object', function() {
  console.log(window.document);
  return {};
});
```
Gives:
```console
residual function at ./p.js:3:33 refers to the following identifiers defined outside of the local scope: console, window
```
How to tell Prepack that `window.*` is free of side effects with all it props of any depth (even if it isn't)?

**Comment by cblappert** [comment]
I made a mistake in one of my previous responses: replace the original `__makePartial` with `__makeSimple` (will edit now).

`__makeSimple` will allow you to go 1 nesting level deep for properties by telling Prepack that those properties have no getters and setters. If you want to go multiple levels deep, you'll have to explicitly specify the properties that are objects and make them simple. Note that properties of simple objects can't really be operated over because Prepack doesn't know their type (they could be a number, object, function etc). This is also why we cannot easily add an annotation to allow Prepack to access arbitrarily nested properties.

If you're trying to use some small enough subset of the DOM, you can try explicitly specifying as little as you need to:
```javascript
this.window = __abstract(
{
  foo: __abstract({})
}, "window");
__makeSimple(window);
__makeSimple(window.foo);
console.log(window.baz);
console.log(window.foo.bar);
// but you can't to window.baz.xyz
```

**Comment by NTillmann** [comment]
It looks like the question got answered.
