### ISSUE TITLE
Implement `requestAnimationFrame` & `cancelAnimationFrame`

### ISSUE THREAD

**Issue by roman01la** [facebook/prepack#626]
I'm not familiar much with prepack internals, but it seems like this could be implemented the way `setTimeout` & `setInterval` are defined here https://github.com/facebook/prepack/blob/57cc59c07d164e4827c24637af9c1002b0c4a3c8/src/intrinsics/dom/global.js#L49-L66

If someone could show me the right direction I would be happy to submit a PR.

**Comment by NTillmann** [comment]
This is part of the bigger effort to implement DOM shims (#24). But if `requestAnimationFrame` & `cancelAnimationFrame` are what you need now, we are happy to take your contribution!

A few things would have to be done to get it fully working:
1. Add implementations exactly mirroring what's happening already for `setTimeout` and `setInternal`.
2. We need to implement the TODO: The call needs to be emitted to the code generator so that it appears in the residual program.

I'll try to create a pull request today for the TODOs, then you can take it from there. Thanks for offering your help!
