### ISSUE TITLE
New proposal

### ISSUE THREAD

**Issue by BrodaNoel** [facebook/prepack#637]
Shouldn't it be just `foo = 3`?
<img width="738" alt="screen shot 2017-05-12 at 5 51 48 pm" src="https://cloud.githubusercontent.com/assets/1837969/26016531/d3a2b67c-373b-11e7-9776-e755a00a8b58.png">

**Comment by BrodaNoel** [comment]
<img width="714" alt="screen shot 2017-05-12 at 5 53 15 pm" src="https://cloud.githubusercontent.com/assets/1837969/26016550/e7209f16-373b-11e7-8239-39b77d2d4c24.png">

**Comment by sebmarkbage** [comment]
If the global object has a setter on it, it needs to be invoked twice.

There is currently no way to use `__makeSimple` on the global object. Otherwise that would be a way to "promise" that the global object doesn't have any setters.

**Comment by hermanventer** [comment]
The main problem with this particular example is that foo is not declared and that we do not assume to know all of the properties of the global object (since that is environment dependent). Hence the possibility that "global.foo" is property with a setter.

Note that we DO assume that the setter, if any, will set set the value of foo to 3 and that it will not have any other side effects visible to the heap that will later be serialized. Adding the assumption that the setter, if any, does not care if it is called does not seem such a great leap, but it does seem to be false for at least one scenario that we care about.
