### ISSUE TITLE
Create a way for Prepack to return a list of errors/warnings to its caller

### ISSUE THREAD

**Issue by hermanventer** [facebook/prepack#675]
While Prepack is doing the its Abstract Interpretation, it may come across execution paths that throw unhandled exceptions or that result in false invariants.

At the moment, things come to a halt when that happens, but that is not always going to be the case when Prepack is running with the --residual option, since it will simply generate code to throw the exception at runtime and carry on.

The resulting code may be just fine in practice if the bad execution paths are infrequently traversed at runtime, but developers may care anyway, in which case it would be helpful if there were a way for them get warnings about this from Prepack.

One possible design is to create a global list of error/warning messages in the Realm and then return the list as part of the Prepack API.

Another possible design is for the calling code to pass in a call back function that will be invoked to report each error/warning as it is encountered. This allows the caller to display these messages as soon as they are generated and it also provides a way for the caller to cancel further Prepack execution.

**Comment by NTillmann** [comment]
I see such a error/warning messaging system as secondary.
First of all, Prepack, "--residual" or not, should simply preserve the program behavior: When the original program (conditionally) throws a particular exception, then the rewritten program should do the same. This makes a lot of sense, also without "--residual", for conditionally thrown exceptions that indicate that very unlikely environment misconfiguration where the developer chose to just throw an exception instead of handling it more gracefully.

**Comment by hershi** [comment]
Addressed by #698
