### ISSUE TITLE
Any way to disable prepack manually?

### ISSUE THREAD

**Issue by galenyuan** [facebook/prepack#703]
Is there any way to disable prepack manually?
Like in ESLint, if I don't want to use eslint in a file, simply use
```javascript
/* eslint-disable */
console.log('hello world')
/* eslint-enable */
```
What about do like this in prepack?
```javascript
/* prepack-disable */
for (let i = 0; i < 99999; i++) {
  console.log(i)
}
/* prepack-enable */
```
so I can do it if I think this block will generate a huge-size-code

**Comment by NTillmann** [comment]
You could leave behind residual code as follows:
```js
__residual("object", function(console) {
for (let i = 0; i < 99999; i++) {
  console.log(i)
}
}, console);
```

Note that you should only do this if the residual code that modify any locations that will get referenced later on.
Also note that the "object" parameter is a bit dubious. We should support "void" here. See https://github.com/facebook/prepack/issues/621.

**Comment by galenyuan** [comment]
It wired, why not do like ESLint?

**Comment by cblappert** [comment]
We agree that the `__residual` function call syntax is clunky and not ideal. We would like to improve it in the future.

We can't disable prepack on arbitrary chunks of code because Prepack works by knowing the whole program and the exact global state. If we pause in the middle of evaluation to skip over some arbitrary code, Prepack doesn't know if it's safe to continue or if that code had some visible side-effects that would make Prepack's output incorrect.

**Comment by NTillmann** [comment]
Looks like the question got answered.
