### ISSUE TITLE
Prepack specific functions

### ISSUE THREAD

**Issue by jakearchibald** [facebook/prepack#828]
It'd be great to be able to prepack specific functions. Eg, given this code:

```js
const hello = 'wor' + 'ld';

function repeat(str) {
  return str.repeat(2);
}

const hellohello = repeat(hello);
```

And an option which expresses "please only prepack 'repeat'", it would output:

```js
const hello = 'wor' + 'ld';

const hellohello = 'worldworld';
```

This means it could be used like a smarter https://www.npmjs.com/package/static-module.

**Comment by hermanventer** [comment]
This would be nice, but a lot of work is needed before we can enable something like that. This is not likely to happen in the next 12 months.

**Comment by jakearchibald** [comment]
It might be that I'm the only person in the world that wants this 😀

**Comment by NTillmann** [comment]
We want it too, but it's really hard, because: JavaScript...
What we are working on for now is prepacking code that runs right from the beginning of time, when everything is perfectly known (as opposed to code that sits somewhere in the middle of the program, at which point so many strange things could have been done to the built-in objects; are you sure that nobody has overridden the `String.prototype.repeat` function?). There's still a lot we want to do around those scenarios.

When that's all done, we'll look further out.

**Comment by NTillmann** [comment]
Closing as there is nothing to do here right now, and we acknowledge that this general idea is something we do want to tackle eventually.
