### ISSUE TITLE
How to delay initialization of third-party code?

### ISSUE THREAD

**Issue by wmertens** [facebook/prepack#879]
I'm giving prepack a go, I already found out I need to not load babel-polyfill when `global.__abstract` exists, but now I'm hitting the initialization function of styled-components which would like to inject a DOM node when a new component is added.

Is there a way to declare a module function as "don't call try to prepack beyond this point, just call the function"?

**Comment by wmertens** [comment]
…and if there is, would it be possible to automatically backtrack on some type of errors and mark that function as non-prepackable?

**Comment by hermanventer** [comment]
You can use global.__residual to prevent Prepack from inlining a function. Note, however, that any effects this function has on the heap will not be visible to Prepack and hence should not be used by any code that will be rewritten by Prepack. If the function has effects that Prepack should know about, you can try wrapping the function inside another function that will be inlined (but that has a residual call to the delayed function) and which modifies the heap with the values Prepack should know about. Note that the delayed function should not throw any exceptions, since Prepack will not produce code that can handle them.

**Comment by wmertens** [comment]
Ok, I think I understand, but I'm having trouble imagining how I would do this for arbitrary third-party modules. What is a good approach?

E.g. if I'm going to use prepack I can tell webpack to replace my dep with an annotated dep, so that part's easy.

However, making the actual annotated dep, should I import it, add `__residual` on all the relevant functions, and then re-export? It seems that the actual return value of `__residual` must be used, so I must monkey-patch the library?

I'm also not sure about the no-side-effects part. I want to pre-calculate css-in-js objects right up to the point where they get registered on a stylesheet, so that the remaining call is the pre-processed css given directly to the stylesheet injection function. I would be wrapping that stylesheet function with `__residual`, as I understand, but of course it will have side effects, are those ok?

Or should I be making that function `__abstract` in this case?

I promise to make a wiki page explaining how to wrap third-party modules once we figure out a nice approach :)

**Comment by hermanventer** [comment]
I think it will suffice to import the library, wrap all functions with wrappers that call the function via __residual, and then to export the wrapped functions. Prepack will strip off the wrappers.

The side effects matter only when a function will be called by Prepack. If a function is simply registered as a call back and called by the host application after the global code has completed then it's side effects will not matter to Prepack.

An __abstract function is something that Prepack can deal with only if it is not called by Prepack.

Perhaps a small example will make it easier to nail down the specifics.
