### ISSUE TITLE
Proposal: New AbstractUnknown value type

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#931]
I'm currently working on a compilation/inlining project for React – the aim is to inline as many components as possible. 

One of the issues I'm facing is that `AbstractValue` and `AbstractObject` aren't perfect for many cases where `props` are passed through the React component tree but are never known because of they dynamic nature. 

I've written a scope/variable scanner that provides basic information (from PropTypes, Flow and from looking for identifier/method accessors in the function) to Prepack's partial evaluator. This helps make inlining possible but I'm struggling with use-cases where conditionals are used with abstract objects/values.

For example:

```js
function MyComponent(props) {
  if (props.foo)
    return props.foo.bar;
  }
  return props.yar;
}
```

If I evaluate the function and pass `props` as an `ObjectValue` with `foo` as a `AbstractObject` property, the component gets evaluated, but because objects are truthy, the conditional statement gets removed – not idea, as the `foo` is not required. If I pass in `foo` as an `AbstractValue`, then obviously it throws an invariant because `bar` property isn't on it.

Ideally, I think there should be a new AbstractUnknown value for these cases that would enable us to evaluate cases that are common in React codebases. It would work like an `AbstractObject` except `mightBeNull`, `mightNotBeObject` etc all work as if it were an `AbstractValue`. The end result would be this, given the example above:

```js
function MyComponent(props) {
  return props.foo ? props.foo.bar : props.yar;
}
```

Let me know if I've not explained anything clearly or want more detail on why this would be good for what we're currently working on. I'd be happy to implement this if I could get some direction on the best way to approach it. Thanks!

**Comment by NTillmann** [comment]
Are you working at the JavaScript source code level, modelling things with `__abstract(...)` values, or are you plugging deeper into the Prepack infrastructure? I am wondering since you refer to internal concepts such as `ObjectValue`, `AbstractValue`, `AbstractObject(Value?)`.

You mention that Prepack "throws an invariant" --- do you mean you get an invariant violation while running Prepack? That should never happen and would be a bug.

It looks to me like `props` should be an ObjectValue that is marked as "simple", e.g. via `__makeSimple(...)` (meaning that properties can be accessed freely on it, without fearing that some property getter screws things up).  That would allow accesses to `.foo` and `.yar`. However, this doesn't solve the `.bar` access problem. So, what can we do?
- A concept like a "deep" or "recursive" simple looks attractive, but that is not without problems.
- One could model `.foo` to be the disjunctive value of either `undefined` or a new simple object; Prepack already has a notion of such value domains that it keeps around for abstract values, however it's not straightforward to write this as a JavaScript model, we could add a new primitive like `__oneOf(val1, val2, ...)`. Then Prepack would explore both branches for the `if` statement. However, what Prepack is still missing is the concept of refinement (#620) that would allow Prepack to deduce in the `then` branch that `.foo` must be the object. @hermanventer considered looking at refinement next, this could be the challenge to solve...

**Comment by trueadm** [comment]
@NTillmann I'm using the internals of Prepack, plugging in bits here and there directly, you can see some of the code here:
https://github.com/trueadm/react/blob/compiler/scripts/compiler/src/evaluator.js

Regarding the invariant, it happens when I calling it via https://github.com/trueadm/react/blob/compiler/scripts/compiler/src/reconciler.js#L97:

I've been working on this with @sebmarkbage, so he might be able to add more clarity to what our intentions are in terms of what we'd like from Prepack. Your second point sounds like the sort of thing we're looking for though :)

**Comment by hermanventer** [comment]
I agree with Nikolai that it would be better to provide a new model function that can construct a abstract value that is the join of undefined and an object. This would be an AbstractValue with a values domain that includes both UndefinedValue and the ObjectValue. We would then rely on refine to get rid of the UndefinedValue.

I'm still mulling over the exact mechanism for doing this, but it is pretty much on top of my todo list.

**Comment by trueadm** [comment]
@hermanventer Awesome stuff – that will help the React compilation efforts hugely. Let me know if there's anything I can help with/test with. :)
